baseURL = "https://chaoray.github.io/"
title = "高中筆記整理"
theme = "hugo-book"

disablePathToLower = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  disableKinds = ['home']
  category = 'categories'
  tag = 'tags'

[params]
  BookToC = true
  BookLogo = 'img/icon.webp'
  BookMenuBundle = '/menu'
  BookServiceWorker = true
  BookComments = true