baseURL: "https://chaoray.github.io/"
languageCode: zh-tw
title: 高中筆記整理
theme: hugo-geekdoc

defaultContentLanguage: zh-tw
defaultContentLanguageInSubdir: true

languages:
  zh-tw:
    languageName: "Traditional-Chinese"
    weight: 1
    profileMode:
      enabled: true
      title: 高中筆記整理
      imageUrl: "img/icon.webp"
      imageWidth: 150
      imageHeight: 150
      buttons:
        - name: 國文
          url: post/chinese
        - name: 英文
          url: post/english
        - name: 數學
          url: post/math
        - name: 自然
          url: post/science
        - name: 社會
          url: post/society
    menu:
      main:
        - identifier: home
          name: 主頁
          url: /
          weight: 1
        - identifier: post
          name: 筆記
          url: post
          weight: 2
        - identifier: search
          name: 搜尋
          url: search
          weight: 4
        - identifier: fastuse
          name: 快速使用
          url: fastuse
          weight: 5
        - identifier: about
          name: 關於
          url: about
          weight: 6
        - identifier: archives
          name: 總覽
          url: archives
          weight: 7

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  # author: ["郭凱明", "姜承恩", "趙文睿"]

  defaultTheme: light
  disableThemeToggle: false

  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCounts: true
  ShowLastMod: true
  VisitCount: true
  hideFooter: false

  socialIcons:
    - name: github
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

  label:
    text: "高中筆記整理"
    icon: "img/icon.webp"
    iconHeight: 35

  assets:
    favicon: "img/icon.webp"
    favicon16x16: "img/icon.webp"
    favicon32x32: "img/icon.webp"
    apple_touch_icon: "img/icon.webp"
    safari_pinned_tab: "img/icon.webp"

  taxonomies:
    category: categories
    tag: tags

  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 1
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary"]

markup:
  goldmark:
    renderer:
      unsafe: true
